#!/usr/bin/env zsh

# --------------------------------------------------------------------------
# External files.
# --------------------------------------------------------------------------

# Load bash profiles from /etc/profile.d
if test -d /etc/profile.d/; then
    for profile in /etc/profile.d/*.sh; do
        test -r "$profile" && . "$profile"
    done
    unset profile
fi

unsetopt nullglob # Globs which don't match anything expand to nothing.
